### PR TITLE
Add support for removing unused .9.png files

### PR DESCRIPTION
**Pull request by ayjindal**
In addition to .png files, this will remove .9.png files too that are unused.

### CODE REVIEW

**Comment by joshruesch** [comment]
Thanks for the pull request by the way!

**Comment by joshruesch** [comment]
I wonder high-level if it'd be easier to manually sub-string off the '.png' or '.9.png'

**Comment by joshruesch** [comment]
Other than that, I think this looks good. Thanks for the addition!

**Comment by ayjindal** [comment]
@joshruesch Can we merge this?

**Comment by joshruesch** [comment]
Looks good to me. @hhoang, will you please merge this in (:

**Comment by hhoang** [comment]
Yeah. Sorry for the delay. Thank you for your contribution @ayjindal!

**Pull request merged**
